trees:
- root: ~/Documents/Apps_via_Git/Theming/Catppuccin
  repos:
  - name: Kvantum
    worktree_setup: false
    remotes:
    - name: origin
      url: https://github.com/catppuccin/Kvantum.git
      type: https
  - name: kitty
    worktree_setup: false
    remotes:
    - name: origin
      url: https://github.com/catppuccin/kitty.git
      type: https
  - name: micro
    worktree_setup: false
    remotes:
    - name: origin
      url: https://github.com/catppuccin/micro.git
      type: https
